
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaPrincipal.java
 *
 * Created on 23/09/2010, 08:57:45
 */

package InterfacesGraficas;

/**
 *
 * @author rustu
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    ChuckNorrisControlador chuck;

    /** Creates new form PantallaPrincipal */
    public PantallaPrincipal(ChuckNorrisControlador chuck) {
        initComponents();
        this.chuck = chuck;
        this.setTitle("Sistema ChuckNorrys powered by Bicentenario");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonera = new javax.swing.JPanel();
        botonEjecutarOrdenesTrabajo = new javax.swing.JButton();
        botonConsultarOrdenesPendientes = new javax.swing.JButton();
        botonConsultarAvanceReclamo = new javax.swing.JButton();
        botonAtenderReclamo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(392, 194));

        panelBotonera.setMaximumSize(new java.awt.Dimension(400, 200));
        panelBotonera.setMinimumSize(new java.awt.Dimension(400, 200));
        panelBotonera.setPreferredSize(new java.awt.Dimension(400, 200));

        botonEjecutarOrdenesTrabajo.setText("CU Ejecutar ordenes de trabajo");
        botonEjecutarOrdenesTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarOrdenesTrabajoActionPerformed(evt);
            }
        });

        botonConsultarOrdenesPendientes.setText("CU Consultar ordenes pendientes");
        botonConsultarOrdenesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarOrdenesPendientesActionPerformed(evt);
            }
        });

        botonConsultarAvanceReclamo.setText("CU Consultar avance de reclamo");
        botonConsultarAvanceReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarAvanceReclamoActionPerformed(evt);
            }
        });

        botonAtenderReclamo.setText("CU Atender Reclamo por desperfecto");
        botonAtenderReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtenderReclamoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/Monster inc.JPG"))); // NOI18N
        jButton1.setText("Me jui pa' mi choza");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoneraLayout = new javax.swing.GroupLayout(panelBotonera);
        panelBotonera.setLayout(panelBotoneraLayout);
        panelBotoneraLayout.setHorizontalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultarAvanceReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(botonAtenderReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(botonConsultarOrdenesPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(botonEjecutarOrdenesTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelBotoneraLayout.setVerticalGroup(
            panelBotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtenderReclamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConsultarAvanceReclamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConsultarOrdenesPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEjecutarOrdenesTrabajo)
                .addGap(15, 15, 15)
                .addComponent(jButton1))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/logo-sys.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtenderReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtenderReclamoActionPerformed

        chuck.iniciarCUAtenderReclamoPorDesperfecto();
    }//GEN-LAST:event_botonAtenderReclamoActionPerformed

    private void botonConsultarAvanceReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarAvanceReclamoActionPerformed
        chuck.iniciarCUConsultarAvanceDeReclamo();  
    }//GEN-LAST:event_botonConsultarAvanceReclamoActionPerformed

    private void botonConsultarOrdenesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarOrdenesPendientesActionPerformed
        chuck.iniciarCUConsultarOrdenesPendientes();
    }//GEN-LAST:event_botonConsultarOrdenesPendientesActionPerformed

    private void botonEjecutarOrdenesTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarOrdenesTrabajoActionPerformed
        chuck.iniciarCUEjecutarOrdenesPendientes();
    }//GEN-LAST:event_botonEjecutarOrdenesTrabajoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtenderReclamo;
    private javax.swing.JButton botonConsultarAvanceReclamo;
    private javax.swing.JButton botonConsultarOrdenesPendientes;
    private javax.swing.JButton botonEjecutarOrdenesTrabajo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panelBotonera;
    // End of variables declaration//GEN-END:variables

}
