
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaAtenderReclamoPorDesperfecto.java
 *
 * Created on 16/09/2010, 17:07:22
 */

package InterfacesGraficas;

import DTO.DTOProblemasDelSemaforo;
import DTO.DTOinfoParaCrearDenuncia;
import Excepciones.ExcepcionDenunciaExistente;
import InterfacesGraficas.ModelosTablas.ModeloJListListaProblemas;
import InterfacesGraficas.ModelosTablas.ModeloTablaSemaforos;
import Persistencia.Entidades.Calle;
import Persistencia.Entidades.Denunciante;
import Persistencia.Entidades.Operador;
import Persistencia.Entidades.OperadorImplementacion;
import Persistencia.Entidades.Problema;
import Persistencia.Entidades.Semaforo;
import Persistencia.Entidades.SuperDruperInterfaz;
import Persistencia.ExpertosPersistencia.Criterio;
import Persistencia.ExpertosPersistencia.FachadaExterna;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;




/**
 *
 * @author diego
 */
public class PantallaAtenderReclamoPorDesperfecto extends javax.swing.JFrame {
    ControladorAtenderReclamoPorDesperfecto controladorARPD;
    int filaSeleccionada = -1;
    DTOinfoParaCrearDenuncia dTOinfoParaCrearDenuncia;
    HashMap<String, DTOProblemasDelSemaforo> hashMapProblemasDelSemaforo;
    Denunciante denunciante;


    /** Creates new form PantallaAtenderReclamoPorDesperfecto */
    public PantallaAtenderReclamoPorDesperfecto(ControladorAtenderReclamoPorDesperfecto controladorARPD) {
        this.controladorARPD = controladorARPD;

        initComponents();
        dTOinfoParaCrearDenuncia = new DTOinfoParaCrearDenuncia();
        dTOinfoParaCrearDenuncia.setProblemasDelSemaforo(new ArrayList<DTOProblemasDelSemaforo>());
        hashMapProblemasDelSemaforo = new HashMap<String, DTOProblemasDelSemaforo>();
        comboCalle1.setModel(new DefaultComboBoxModel());
        comboCalle2.setModel(new DefaultComboBoxModel());
        todosLosProblemas.setModel(new ModeloJListListaProblemas());
        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas());
        tablaDeSemafor.setModel(new ModeloTablaSemaforos());
        tablaDeSemafor.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
                 int fila = tablaDeSemafor.rowAtPoint(e.getPoint());
                 int columna = tablaDeSemafor.columnAtPoint(e.getPoint());
                 if ((fila > -1) && (columna > -1)){
                    filaSeleccionada = fila;
                    ModeloTablaSemaforos mod = (ModeloTablaSemaforos)tablaDeSemafor.getModel();
                    Semaforo sem = (Semaforo) mod.getRow(filaSeleccionada);
                    if(hashMapProblemasDelSemaforo.containsKey(sem.getnumeroSerie()))
                        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas(hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas()));
                    else
                        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas());


                    }
                    }
            });




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoInterseccionCalle = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarDNI = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        guardarInfoDenunciante = new javax.swing.JButton();
        celular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        calle2 = new javax.swing.JTextField();
        calle1 = new javax.swing.JTextField();
        buscarInteseccion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        validarCalles = new javax.swing.JButton();
        comboCalle1 = new javax.swing.JComboBox();
        comboCalle2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeSemafor = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        agregarProblema = new javax.swing.JButton();
        quitarProblema = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        todosLosProblemas = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        problemasDeCadaSemaforo = new javax.swing.JList();
        asentarCaso = new javax.swing.JButton();
        cancelarCaso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Denunciante"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 184, -1));

        jLabel1.setText("DNI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        buscarDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/Search-20.png"))); // NOI18N
        buscarDNI.setText("Buscar");
        buscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDNIActionPerformed(evt);
            }
        });
        jPanel1.add(buscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 130, -1));

        nombre.setText("Nombre");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        apellido.setText("Apellido");
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Domicilio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 14));
        jPanel1.add(domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, -1));

        jLabel6.setText("E-mail:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 390, 10));

        guardarInfoDenunciante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/add_user-20.png"))); // NOI18N
        guardarInfoDenunciante.setText("Guardar");
        guardarInfoDenunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarInfoDenuncianteActionPerformed(evt);
            }
        });
        jPanel1.add(guardarInfoDenunciante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 130, -1));
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 160, -1));

        jLabel3.setText("Celular");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, 452, 330));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicación"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("calle 1");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setText("calle 2");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 42, -1));
        jPanel2.add(calle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, -1));
        jPanel2.add(calle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 150, -1));

        buscarInteseccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/Search-20.png"))); // NOI18N
        buscarInteseccion.setText("Buscar");
        buscarInteseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarInteseccionActionPerformed(evt);
            }
        });
        jPanel2.add(buscarInteseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 110, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 420, 10));
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 70, -1));

        jLabel10.setText("Altura");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        grupoInterseccionCalle.add(jRadioButton1);
        jRadioButton1.setText("Intersección");
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        grupoInterseccionCalle.add(jRadioButton2);
        jRadioButton2.setText("Calle Simple");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        validarCalles.setText("Buscar coincidencia");
        validarCalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarCallesActionPerformed(evt);
            }
        });
        jPanel2.add(validarCalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        comboCalle1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCalle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCalle1ActionPerformed(evt);
            }
        });
        jPanel2.add(comboCalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, -1));

        comboCalle2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboCalle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 452, 192));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Semáforos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeSemafor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDeSemafor);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 33, 600, 174));

        jLabel12.setText("Problemas");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        agregarProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/right-20.png"))); // NOI18N
        agregarProblema.setText("Agregar");
        agregarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProblemaActionPerformed(evt);
            }
        });
        jPanel3.add(agregarProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, -1));

        quitarProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/left-20.png"))); // NOI18N
        quitarProblema.setText("Quitar");
        quitarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarProblemaActionPerformed(evt);
            }
        });
        jPanel3.add(quitarProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, -1));

        jLabel13.setText("Problemas a Cargar");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 14));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 590, 10));

        todosLosProblemas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(todosLosProblemas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 100));

        problemasDeCadaSemaforo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(problemasDeCadaSemaforo);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 170, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 86, 651, 407));

        asentarCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/save-20.png"))); // NOI18N
        asentarCaso.setText("Asentar Caso");
        asentarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asentarCasoActionPerformed(evt);
            }
        });
        getContentPane().add(asentarCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 160, -1));

        cancelarCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/Shutdown-20.png"))); // NOI18N
        cancelarCaso.setText("Cancelar");
        cancelarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCasoActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/new-cabecera.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProblemaActionPerformed
        
        ModeloTablaSemaforos modTablaSem = (ModeloTablaSemaforos)tablaDeSemafor.getModel();
        Semaforo sem = (Semaforo) modTablaSem.getRow(filaSeleccionada);
        ModeloJListListaProblemas modTodosLosProblemas = (ModeloJListListaProblemas) todosLosProblemas.getModel();
        boolean guardarProblema;
        if(hashMapProblemasDelSemaforo.get(sem.getnumeroSerie())!=null){
            Problema problemaAGuardar = (Problema) modTodosLosProblemas.getElementAt(todosLosProblemas.getSelectedIndex());
            guardarProblema = true;
            for(Problema prob : hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas()){
                if(prob.getcodigoProblema() == problemaAGuardar.getcodigoProblema())
                    guardarProblema = false;
                
            }
            if(guardarProblema)
                hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas().add(problemaAGuardar);
        }
        else{
            DTOProblemasDelSemaforo dtoprobDSem = new DTOProblemasDelSemaforo();
            dtoprobDSem.setSemaforo(sem);
            dtoprobDSem.setListaDeProblemas(new ArrayList<Problema>());
            hashMapProblemasDelSemaforo.put(sem.getnumeroSerie(),dtoprobDSem);
            hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas().add((Problema) modTodosLosProblemas.getElementAt(todosLosProblemas.getSelectedIndex()));
        }
        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas((hashMapProblemasDelSemaforo.get(sem.getnumeroSerie())).getListaDeProblemas()));
}//GEN-LAST:event_agregarProblemaActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void buscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDNIActionPerformed
        denunciante = controladorARPD.buscarDenunciante(dni.getText());
        apellido.setText(denunciante.getPersonaPadron().getapellido());
        nombre.setText(denunciante.getPersonaPadron().getnombre());
        if(denunciante.getdomicilio()!=null)
            domicilio.setText(denunciante.getdomicilio());
        else
            domicilio.setText(denunciante.getPersonaPadron().getdomicilio());
        telefono.setText(denunciante.gettelefonofijo());
        email.setText(denunciante.getemail());
        celular.setText(denunciante.getcelular());

    }//GEN-LAST:event_buscarDNIActionPerformed

    private void validarCallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarCallesActionPerformed

        comboCalle1.setModel(new DefaultComboBoxModel(controladorARPD.buscarCalle(calle1.getText())));
        comboCalle2.setModel(new DefaultComboBoxModel(controladorARPD.buscarCalle(calle2.getText())));


    }//GEN-LAST:event_validarCallesActionPerformed






    private void buscarInteseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarInteseccionActionPerformed

        controladorARPD.buscarSemaforo((Calle)comboCalle1.getSelectedItem(), (Calle)comboCalle2.getSelectedItem());

    }//GEN-LAST:event_buscarInteseccionActionPerformed

    private void quitarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarProblemaActionPerformed

        ModeloTablaSemaforos mod = (ModeloTablaSemaforos)tablaDeSemafor.getModel();
        Semaforo sem = (Semaforo) mod.getRow(filaSeleccionada);
        //ModeloJListListaProblemas mod = (ModeloJListListaProblemas) problemasDeCadaSemaforo.getModel();
        //mod.addElement((Problema) todosLosProblemas.getModel().getElementAt(todosLosProblemas.getSelectedIndex()));
        Problema prob = (Problema) problemasDeCadaSemaforo.getModel().getElementAt(problemasDeCadaSemaforo.getSelectedIndex());
        DTOProblemasDelSemaforo dtoProbDeSem = hashMapProblemasDelSemaforo.get(sem.getnumeroSerie());
        for(int i=0; i<dtoProbDeSem.getListaDeProblemas().size();i++){
            if(dtoProbDeSem.getListaDeProblemas().get(i).getcodigoProblema()==prob.getcodigoProblema())
                dtoProbDeSem.getListaDeProblemas().remove(i);

        }
        if(dtoProbDeSem.getListaDeProblemas().isEmpty()){
            problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas());
        }
        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas((hashMapProblemasDelSemaforo.get(sem.getnumeroSerie())).getListaDeProblemas()));
    }//GEN-LAST:event_quitarProblemaActionPerformed

    private void asentarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asentarCasoActionPerformed
        dTOinfoParaCrearDenuncia.setDenunciante(denunciante);

        //Estos DATOS LOS TIENE QUE DEVOLVER EL SISTMEA DE LOGUEO
        List<Criterio> listaDeCriterios = new ArrayList<Criterio>();
        listaDeCriterios.add(FachadaExterna.getInstancia().crearCriterio("Legajo", "=", "2222"));
        List<SuperDruperInterfaz> listaDeInterfaces = FachadaExterna.getInstancia().buscar("Operador", listaDeCriterios);
        Operador opera = (Operador)listaDeInterfaces.get(0);
        //HASTA ACA
        dTOinfoParaCrearDenuncia.setOperador(opera);
        dTOinfoParaCrearDenuncia.getProblemasDelSemaforo().addAll(hashMapProblemasDelSemaforo.values());        
        controladorARPD.guardarDenuncia(dTOinfoParaCrearDenuncia);        
    }//GEN-LAST:event_asentarCasoActionPerformed

    private void guardarInfoDenuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarInfoDenuncianteActionPerformed
        denunciante.setdomicilio(domicilio.getText());
        denunciante.setemail(email.getText());
        denunciante.settelefonofijo(telefono.getText());
        denunciante.setcelular(celular.getText());
        controladorARPD.guardarDenunciante(denunciante);
    }//GEN-LAST:event_guardarInfoDenuncianteActionPerformed

    private void cancelarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCasoActionPerformed
        controladorARPD.cerrar();

    }//GEN-LAST:event_cancelarCasoActionPerformed

    private void comboCalle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCalle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCalle1ActionPerformed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAtenderReclamoPorDesperfecto().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProblema;
    private javax.swing.JLabel apellido;
    private javax.swing.JButton asentarCaso;
    private javax.swing.JButton buscarDNI;
    private javax.swing.JButton buscarInteseccion;
    private javax.swing.JTextField calle1;
    private javax.swing.JTextField calle2;
    private javax.swing.JButton cancelarCaso;
    private javax.swing.JTextField celular;
    private javax.swing.JComboBox comboCalle1;
    private javax.swing.JComboBox comboCalle2;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField domicilio;
    private javax.swing.JTextField email;
    private javax.swing.ButtonGroup grupoInterseccionCalle;
    private javax.swing.JButton guardarInfoDenunciante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel nombre;
    private javax.swing.JList problemasDeCadaSemaforo;
    private javax.swing.JButton quitarProblema;
    private javax.swing.JTable tablaDeSemafor;
    private javax.swing.JTextField telefono;
    private javax.swing.JList todosLosProblemas;
    private javax.swing.JButton validarCalles;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tablaDeSemafor
     */
    public javax.swing.JTable getTablaDeSemafor() {
        return tablaDeSemafor;
    }

    /**
     * @param tablaDeSemafor the tablaDeSemafor to set
     */
    public void setTablaDeSemafor(javax.swing.JTable tablaDeSemafor) {
        this.tablaDeSemafor = tablaDeSemafor;
    }

    /**
     * @return the problemasDeCadaSemaforo
     */
    public javax.swing.JList getProblemasDeCadaSemaforo() {
        return problemasDeCadaSemaforo;
    }

    /**
     * @param problemasDeCadaSemaforo the problemasDeCadaSemaforo to set
     */
    public void setProblemasDeCadaSemaforo(JList problemasDeCadaSemaforo) {
        this.problemasDeCadaSemaforo = problemasDeCadaSemaforo;
    }

    /**
     * @return the todosLosProblemas
     */
    public javax.swing.JList getTodosLosProblemas() {
        return todosLosProblemas;
    }

    /**
     * @param todosLosProblemas the todosLosProblemas to set
     */
    public void setTodosLosProblemas(javax.swing.JList todosLosProblemas) {
        this.todosLosProblemas = todosLosProblemas;
    }

}
