
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaAtenderReclamoPorDesperfecto.java
 *
 * Created on 16/09/2010, 17:07:22
 */

package InterfacesGraficas;

import DTO.DTOProblemasDelSemaforo;
import DTO.DTOinfoParaCrearDenuncia;
import Excepciones.ExcepcionObjetoNoEncontrado;
import InterfacesGraficas.ModelosTablas.ModeloJListListaProblemas;
import InterfacesGraficas.ModelosTablas.ModeloTablaSemaforos;
import Persistencia.Entidades.Calle;
import Persistencia.Entidades.Denunciante;
import Persistencia.Entidades.Problema;
import Persistencia.Entidades.Semaforo;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;




/**
 *
 * @author diego
 */
public class PantallaAtenderReclamoPorDesperfecto extends javax.swing.JFrame {

   // private File archivoAudio;//archivo de Audio a reproducir
    //bs reproductor = new bs();
    ControladorAtenderReclamoPorDesperfecto controladorARPD;
    int filaSeleccionada = -1;
    DTOinfoParaCrearDenuncia dTOinfoParaCrearDenuncia;
    HashMap<String, DTOProblemasDelSemaforo> hashMapProblemasDelSemaforo;
    Denunciante denunciante;


    /** Creates new form PantallaAtenderReclamoPorDesperfecto */
    public PantallaAtenderReclamoPorDesperfecto(ControladorAtenderReclamoPorDesperfecto controladorARPD) {
        this.controladorARPD = controladorARPD;

        initComponents();
        ponerTodoEnBlanco();

        tablaDeSemafor.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
                 int fila = tablaDeSemafor.rowAtPoint(e.getPoint());
                 int columna = tablaDeSemafor.columnAtPoint(e.getPoint());
                 if ((fila > -1) && (columna > -1)){
                    filaSeleccionada = fila;
                    ModeloTablaSemaforos mod = (ModeloTablaSemaforos)tablaDeSemafor.getModel();
                    Semaforo sem = (Semaforo) mod.getRow(filaSeleccionada);
                    if(hashMapProblemasDelSemaforo.containsKey(sem.getnumeroSerie()))
                        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas(hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas()));
                    else
                        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas());


                    }
                    }
            });




    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoInterseccionCalle = new javax.swing.ButtonGroup();
        denunciaExistente = new javax.swing.JDialog(this);
        jLabel7 = new javax.swing.JLabel();
        aceptarDenunciaExistente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numeroDeDenunciaDenunciaExistente = new javax.swing.JLabel();
        cantidadDeReclamosDenunciaExistente = new javax.swing.JLabel();
        denunciaGuardada = new javax.swing.JDialog(this);
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        aceptarDenunciaGuardad = new javax.swing.JButton();
        denunciaReclamo = new javax.swing.JLabel();
        codigoDenunciaReclamo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarDNI = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        guardarInfoDenunciante = new javax.swing.JButton();
        celular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        calle2 = new javax.swing.JTextField();
        calle1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        interseccionRadioButton = new javax.swing.JRadioButton();
        calleSimpleRadioButton = new javax.swing.JRadioButton();
        validarCalles = new javax.swing.JButton();
        comboCalle1 = new javax.swing.JComboBox();
        comboCalle2 = new javax.swing.JComboBox();
        altura = new javax.swing.JComboBox();
        consultarAvanceDeReclamo = new javax.swing.JButton();
        buscarInteseccion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDeSemafor = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        agregarProblema = new javax.swing.JButton();
        quitarProblema = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        todosLosProblemas = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        problemasDeCadaSemaforo = new javax.swing.JList();
        asentarCaso = new javax.swing.JButton();
        cancelarCaso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        denunciaExistente.setTitle("Atención");

        jLabel7.setText("DENUNCIA EXISTENTE");

        aceptarDenunciaExistente.setText("Aceptar");
        aceptarDenunciaExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarDenunciaExistenteActionPerformed(evt);
            }
        });

        jLabel11.setText("Cantidad de reclamos:");

        jLabel14.setText("Número de denuncia:");

        numeroDeDenunciaDenunciaExistente.setText(" ");

        cantidadDeReclamosDenunciaExistente.setText(" ");

        javax.swing.GroupLayout denunciaExistenteLayout = new javax.swing.GroupLayout(denunciaExistente.getContentPane());
        denunciaExistente.getContentPane().setLayout(denunciaExistenteLayout);
        denunciaExistenteLayout.setHorizontalGroup(
            denunciaExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denunciaExistenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(denunciaExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(denunciaExistenteLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroDeDenunciaDenunciaExistente))
                    .addGroup(denunciaExistenteLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(cantidadDeReclamosDenunciaExistente)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, denunciaExistenteLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(aceptarDenunciaExistente)
                .addContainerGap())
        );
        denunciaExistenteLayout.setVerticalGroup(
            denunciaExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denunciaExistenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(denunciaExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(numeroDeDenunciaDenunciaExistente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(denunciaExistenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cantidadDeReclamosDenunciaExistente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(aceptarDenunciaExistente)
                .addContainerGap())
        );

        denunciaGuardada.setTitle("¡¡ENHORABUENA!!");
        denunciaGuardada.setAlwaysOnTop(true);

        jLabel15.setText("Se generó un/una:");

        jLabel16.setText("Código: ");

        aceptarDenunciaGuardad.setText("Aceptar");
        aceptarDenunciaGuardad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarDenunciaGuardadActionPerformed(evt);
            }
        });

        denunciaReclamo.setText(" ");

        codigoDenunciaReclamo.setText(" ");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/enhorabuena.JPG"))); // NOI18N

        javax.swing.GroupLayout denunciaGuardadaLayout = new javax.swing.GroupLayout(denunciaGuardada.getContentPane());
        denunciaGuardada.getContentPane().setLayout(denunciaGuardadaLayout);
        denunciaGuardadaLayout.setHorizontalGroup(
            denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denunciaGuardadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(denunciaGuardadaLayout.createSequentialGroup()
                            .addGroup(denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(denunciaGuardadaLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(denunciaReclamo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                .addGroup(denunciaGuardadaLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(codigoDenunciaReclamo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, denunciaGuardadaLayout.createSequentialGroup()
                            .addComponent(aceptarDenunciaGuardad)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, denunciaGuardadaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap())))
        );
        denunciaGuardadaLayout.setVerticalGroup(
            denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denunciaGuardadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(denunciaReclamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(denunciaGuardadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(codigoDenunciaReclamo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(aceptarDenunciaGuardad)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Denunciante"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dni.setNextFocusableComponent(buscarDNI);
        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 184, -1));

        jLabel1.setText("DNI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        buscarDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/edit-find.png"))); // NOI18N
        buscarDNI.setText("Buscar");
        buscarDNI.setNextFocusableComponent(domicilio);
        buscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDNIActionPerformed(evt);
            }
        });
        jPanel1.add(buscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 130, -1));

        nombre.setText("Nombre");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        apellido.setText("Apellido");
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Domicilio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 14));

        domicilio.setNextFocusableComponent(celular);
        jPanel1.add(domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, -1));

        jLabel5.setText("Teléfono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        telefono.setNextFocusableComponent(email);
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, -1));

        jLabel6.setText("E-mail:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        email.setNextFocusableComponent(guardarInfoDenunciante);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 390, 10));

        guardarInfoDenunciante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/contact-new.png"))); // NOI18N
        guardarInfoDenunciante.setText("Guardar");
        guardarInfoDenunciante.setNextFocusableComponent(interseccionRadioButton);
        guardarInfoDenunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarInfoDenuncianteActionPerformed(evt);
            }
        });
        jPanel1.add(guardarInfoDenunciante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 130, -1));

        celular.setNextFocusableComponent(telefono);
        jPanel1.add(celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 160, -1));

        jLabel3.setText("Celular");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, 452, 330));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicación"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("calle 1");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel9.setText("calle 2");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 42, -1));

        calle2.setNextFocusableComponent(validarCalles);
        jPanel2.add(calle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, -1));

        calle1.setNextFocusableComponent(calle2);
        jPanel2.add(calle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 10));

        jLabel10.setText("Altura");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        grupoInterseccionCalle.add(interseccionRadioButton);
        interseccionRadioButton.setText("Intersección");
        interseccionRadioButton.setNextFocusableComponent(calleSimpleRadioButton);
        interseccionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interseccionRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(interseccionRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        grupoInterseccionCalle.add(calleSimpleRadioButton);
        calleSimpleRadioButton.setText("Calle Simple");
        calleSimpleRadioButton.setNextFocusableComponent(calle1);
        calleSimpleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleSimpleRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(calleSimpleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        validarCalles.setText("Buscar coincidencia");
        validarCalles.setNextFocusableComponent(buscarInteseccion);
        validarCalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarCallesActionPerformed(evt);
            }
        });
        jPanel2.add(validarCalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        comboCalle1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCalle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCalle1ActionPerformed(evt);
            }
        });
        jPanel2.add(comboCalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 130, -1));

        comboCalle2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboCalle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, -1));

        altura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, -1));

        consultarAvanceDeReclamo.setText("Consultar Avance de Reclamo");
        consultarAvanceDeReclamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarAvanceDeReclamoActionPerformed(evt);
            }
        });
        jPanel2.add(consultarAvanceDeReclamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 210, 30));

        buscarInteseccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/edit-find.png"))); // NOI18N
        buscarInteseccion.setText("Buscar");
        buscarInteseccion.setNextFocusableComponent(tablaDeSemafor);
        buscarInteseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarInteseccionActionPerformed(evt);
            }
        });
        jPanel2.add(buscarInteseccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 452, 192));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Semáforos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDeSemafor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDeSemafor.setNextFocusableComponent(agregarProblema);
        jScrollPane1.setViewportView(tablaDeSemafor);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 33, 600, 174));

        jLabel12.setText("Problemas");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        agregarProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/go-next.png"))); // NOI18N
        agregarProblema.setText("Agregar");
        agregarProblema.setNextFocusableComponent(quitarProblema);
        agregarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProblemaActionPerformed(evt);
            }
        });
        jPanel3.add(agregarProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, -1));

        quitarProblema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/go-previous.png"))); // NOI18N
        quitarProblema.setText("Quitar");
        quitarProblema.setNextFocusableComponent(asentarCaso);
        quitarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarProblemaActionPerformed(evt);
            }
        });
        jPanel3.add(quitarProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, -1));

        jLabel13.setText("Problemas a Cargar");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 14));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 590, 10));

        todosLosProblemas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(todosLosProblemas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 100));

        problemasDeCadaSemaforo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(problemasDeCadaSemaforo);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 170, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 86, 651, 407));

        asentarCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/document-save.png"))); // NOI18N
        asentarCaso.setText("Asentar Caso");
        asentarCaso.setNextFocusableComponent(cancelarCaso);
        asentarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asentarCasoActionPerformed(evt);
            }
        });
        getContentPane().add(asentarCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 160, -1));

        cancelarCaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/iconos/system-shutdown-panel.png"))); // NOI18N
        cancelarCaso.setText("Cancelar");
        cancelarCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCasoActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarCaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilidades/Imagenes/new-cabecera.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProblemaActionPerformed
        
        ModeloTablaSemaforos modTablaSem = (ModeloTablaSemaforos)tablaDeSemafor.getModel();
        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un semáforo", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            Semaforo sem = (Semaforo) modTablaSem.getRow(filaSeleccionada);
            ModeloJListListaProblemas modTodosLosProblemas = (ModeloJListListaProblemas) todosLosProblemas.getModel();
            boolean guardarProblema;
            if(todosLosProblemas.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(rootPane, "Seleccione un problema", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                if(hashMapProblemasDelSemaforo.get(sem.getnumeroSerie())!=null){
                    Problema problemaAGuardar = (Problema) modTodosLosProblemas.getElementAt(todosLosProblemas.getSelectedIndex());
                    guardarProblema = true;
                    for(Problema prob : hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas()){
                        if(prob.getcodigoProblema() == problemaAGuardar.getcodigoProblema())
                            guardarProblema = false;

                    }
                    if(guardarProblema)
                        hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas().add(problemaAGuardar);
                }
                else{
                    DTOProblemasDelSemaforo dtoprobDSem = new DTOProblemasDelSemaforo();
                    dtoprobDSem.setSemaforo(sem);
                    dtoprobDSem.setListaDeProblemas(new ArrayList<Problema>());
                    hashMapProblemasDelSemaforo.put(sem.getnumeroSerie(),dtoprobDSem);
                    hashMapProblemasDelSemaforo.get(sem.getnumeroSerie()).getListaDeProblemas().add((Problema) modTodosLosProblemas.getElementAt(todosLosProblemas.getSelectedIndex()));
                }
                problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas((hashMapProblemasDelSemaforo.get(sem.getnumeroSerie())).getListaDeProblemas()));
            }
        }
}//GEN-LAST:event_agregarProblemaActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void buscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDNIActionPerformed
        if(dni.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(rootPane, "No ha ingresado el DNI del denunciante", "ERROR", JOptionPane.WARNING_MESSAGE);
            
        }else{
            try {
                denunciante = controladorARPD.buscarDenunciante(dni.getText());
                apellido.setText(denunciante.getPersonaPadron().getapellido());
                nombre.setText(denunciante.getPersonaPadron().getnombre());
                if (denunciante.getdomicilio() != null && !denunciante.getdomicilio().equals("")) {
                    domicilio.setText(denunciante.getdomicilio());
                } else {
                    domicilio.setText(denunciante.getPersonaPadron().getdomicilio());
                    denunciante.setdomicilio(denunciante.getPersonaPadron().getdomicilio());
                }
                telefono.setText(denunciante.gettelefonofijo());
                email.setText(denunciante.getemail());
                celular.setText(denunciante.getcelular());
            } catch (ExcepcionObjetoNoEncontrado ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_buscarDNIActionPerformed

    private void validarCallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarCallesActionPerformed

        comboCalle1.setModel(new DefaultComboBoxModel(controladorARPD.buscarCalle(calle1.getText())));
        hashMapProblemasDelSemaforo = new HashMap<String, DTOProblemasDelSemaforo>();
        problemasDeCadaSemaforo.setModel(new DefaultComboBoxModel());
        consultarAvanceDeReclamo.setEnabled(true);
        if(interseccionRadioButton.isSelected())
            comboCalle2.setModel(new DefaultComboBoxModel(controladorARPD.buscarCalle(calle2.getText())));
        else
            controladorARPD.buscarAlturas((Calle)comboCalle1.getSelectedItem());

    }//GEN-LAST:event_validarCallesActionPerformed






    private void buscarInteseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarInteseccionActionPerformed

        if(comboCalle1.getModel().getSize()==0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado alguna calle 1", "ERROR", JOptionPane.WARNING_MESSAGE);

        }else{
            hashMapProblemasDelSemaforo = new HashMap<String, DTOProblemasDelSemaforo>();
            problemasDeCadaSemaforo.setModel(new DefaultComboBoxModel());
            if(interseccionRadioButton.isSelected()){
                if(comboCalle2.getModel().getSize()==0){
                    JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado alguna calle 2", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else{
                    controladorARPD.buscarSemaforo((Calle)comboCalle1.getSelectedItem(), (Calle)comboCalle2.getSelectedItem());
                }
            } else {
                if(altura.getModel().getSize()==0){
                    JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado alguna altura", "ERROR", JOptionPane.WARNING_MESSAGE);
                }else{
                    controladorARPD.buscarSemaforo((Calle)comboCalle1.getSelectedItem(), ((Integer)altura.getSelectedItem()));
                }
            }
        }
    }//GEN-LAST:event_buscarInteseccionActionPerformed

    private void quitarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarProblemaActionPerformed

        if(filaSeleccionada == -1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un semáforo", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
            ModeloTablaSemaforos mod = (ModeloTablaSemaforos)tablaDeSemafor.getModel();
            Semaforo sem = (Semaforo) mod.getRow(filaSeleccionada);
            //ModeloJListListaProblemas mod = (ModeloJListListaProblemas) problemasDeCadaSemaforo.getModel();
            //mod.addElement((Problema) todosLosProblemas.getModel().getElementAt(todosLosProblemas.getSelectedIndex()));
            if(problemasDeCadaSemaforo.getSelectedIndex() == -1){
                if(problemasDeCadaSemaforo.getModel().getSize()!=0)
                    JOptionPane.showMessageDialog(rootPane, "Seleccione un problema", "ERROR", JOptionPane.WARNING_MESSAGE);
                else
                    JOptionPane.showMessageDialog(rootPane, "El semáforo no tiene problemas asociados", "ERROR", JOptionPane.WARNING_MESSAGE);
            }else{
                Problema prob = (Problema) problemasDeCadaSemaforo.getModel().getElementAt(problemasDeCadaSemaforo.getSelectedIndex());
                DTOProblemasDelSemaforo dtoProbDeSem = hashMapProblemasDelSemaforo.get(sem.getnumeroSerie());
                for(int i=0; i<dtoProbDeSem.getListaDeProblemas().size();i++){
                    if(dtoProbDeSem.getListaDeProblemas().get(i).getcodigoProblema()==prob.getcodigoProblema())
                        dtoProbDeSem.getListaDeProblemas().remove(i);

                }
                if(dtoProbDeSem.getListaDeProblemas().isEmpty()){
                    problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas());
                }
                problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas((hashMapProblemasDelSemaforo.get(sem.getnumeroSerie())).getListaDeProblemas()));
            }
        }
    }//GEN-LAST:event_quitarProblemaActionPerformed

    private void asentarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asentarCasoActionPerformed
        if(denunciante==null){
            JOptionPane.showMessageDialog(rootPane, "No se ha buscado un denunciante", "ERROR", JOptionPane.WARNING_MESSAGE);
        
        }else if(hashMapProblemasDelSemaforo.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No se han seleccionado semáforo con problemas", "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else {

            dTOinfoParaCrearDenuncia.setDenunciante(denunciante);

            /*
            //Estos DATOS LOS TIENE QUE DEVOLVER EL SISTMEA DE LOGUEO
             * AHORA SE CARGAN EN EL CONTROLADOR!!!
            
            List<Criterio> listaDeCriterios = new ArrayList<Criterio>();
            listaDeCriterios.add(FachadaExterna.getInstancia().crearCriterio("Legajo", "=", "2222"));
            List<SuperDruperInterfaz> listaDeInterfaces = FachadaExterna.getInstancia().buscar("Operador", listaDeCriterios);
            Operador opera = (Operador)listaDeInterfaces.get(0);
             *
            
            dTOinfoParaCrearDenuncia.setOperador(opera);
             *  */
            //HASTA ACA
             
            dTOinfoParaCrearDenuncia.getProblemasDelSemaforo().addAll(hashMapProblemasDelSemaforo.values());
            try {
                controladorARPD.guardarDenuncia(dTOinfoParaCrearDenuncia);
            
            } catch (Exception ex) {
                Logger.getLogger(PantallaAtenderReclamoPorDesperfecto.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        

        }
    }//GEN-LAST:event_asentarCasoActionPerformed

    private void guardarInfoDenuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarInfoDenuncianteActionPerformed
        if(denunciante==null){
            JOptionPane.showMessageDialog(rootPane, "No se ha buscado un denunciante", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        denunciante.setdomicilio(domicilio.getText());
        denunciante.setemail(email.getText());
        denunciante.settelefonofijo(telefono.getText());
        denunciante.setcelular(celular.getText());
        controladorARPD.guardarDenunciante(denunciante);
        }
    }//GEN-LAST:event_guardarInfoDenuncianteActionPerformed

    private void cancelarCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCasoActionPerformed
        controladorARPD.cerrar();

    }//GEN-LAST:event_cancelarCasoActionPerformed

    private void comboCalle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCalle1ActionPerformed

        if(calleSimpleRadioButton.isSelected())
            controladorARPD.buscarAlturas((Calle)comboCalle1.getSelectedItem());

    }//GEN-LAST:event_comboCalle1ActionPerformed

    private void interseccionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interseccionRadioButtonActionPerformed

        altura.setModel(new DefaultComboBoxModel());
        altura.setEnabled(false);
        calle2.setEditable(true);
        calle1.setText("");
        comboCalle2.setEnabled(true);
        comboCalle1.setModel(new DefaultComboBoxModel());
        hashMapProblemasDelSemaforo = new HashMap<String, DTOProblemasDelSemaforo>();
        problemasDeCadaSemaforo.setModel(new DefaultComboBoxModel());
        consultarAvanceDeReclamo.setEnabled(false);
        
    }//GEN-LAST:event_interseccionRadioButtonActionPerformed

    private void calleSimpleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleSimpleRadioButtonActionPerformed
        calle2.setEditable(false);
        comboCalle2.setEnabled(false);
        altura.setEnabled(true);
        calle2.setText("");
        calle1.setText("");
        comboCalle2.setModel(new DefaultComboBoxModel());
        comboCalle1.setModel(new DefaultComboBoxModel());
        hashMapProblemasDelSemaforo = new HashMap<String, DTOProblemasDelSemaforo>();
        problemasDeCadaSemaforo.setModel(new DefaultComboBoxModel());
        consultarAvanceDeReclamo.setEnabled(false);
    }//GEN-LAST:event_calleSimpleRadioButtonActionPerformed

    private void aceptarDenunciaGuardadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarDenunciaGuardadActionPerformed
        denunciaGuardada.setVisible(false);
    }//GEN-LAST:event_aceptarDenunciaGuardadActionPerformed

    private void aceptarDenunciaExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarDenunciaExistenteActionPerformed
        denunciaExistente.setVisible(false);
    }//GEN-LAST:event_aceptarDenunciaExistenteActionPerformed

    private void consultarAvanceDeReclamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarAvanceDeReclamoActionPerformed
        controladorARPD.consultarAvanceDeReclamo();
    }//GEN-LAST:event_consultarAvanceDeReclamoActionPerformed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaAtenderReclamoPorDesperfecto().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarDenunciaExistente;
    private javax.swing.JButton aceptarDenunciaGuardad;
    private javax.swing.JButton agregarProblema;
    private javax.swing.JComboBox altura;
    private javax.swing.JLabel apellido;
    private javax.swing.JButton asentarCaso;
    private javax.swing.JButton buscarDNI;
    private javax.swing.JButton buscarInteseccion;
    private javax.swing.JTextField calle1;
    private javax.swing.JTextField calle2;
    private javax.swing.JRadioButton calleSimpleRadioButton;
    private javax.swing.JButton cancelarCaso;
    private javax.swing.JLabel cantidadDeReclamosDenunciaExistente;
    private javax.swing.JTextField celular;
    private javax.swing.JLabel codigoDenunciaReclamo;
    private javax.swing.JComboBox comboCalle1;
    private javax.swing.JComboBox comboCalle2;
    private javax.swing.JButton consultarAvanceDeReclamo;
    private javax.swing.JDialog denunciaExistente;
    private javax.swing.JDialog denunciaGuardada;
    private javax.swing.JLabel denunciaReclamo;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField domicilio;
    private javax.swing.JTextField email;
    private javax.swing.ButtonGroup grupoInterseccionCalle;
    private javax.swing.JButton guardarInfoDenunciante;
    private javax.swing.JRadioButton interseccionRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numeroDeDenunciaDenunciaExistente;
    private javax.swing.JList problemasDeCadaSemaforo;
    private javax.swing.JButton quitarProblema;
    private javax.swing.JTable tablaDeSemafor;
    private javax.swing.JTextField telefono;
    private javax.swing.JList todosLosProblemas;
    private javax.swing.JButton validarCalles;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tablaDeSemafor
     */
    public javax.swing.JTable getTablaDeSemafor() {
        return tablaDeSemafor;
    }

    /**
     * @param tablaDeSemafor the tablaDeSemafor to set
     */
    public void setTablaDeSemafor(javax.swing.JTable tablaDeSemafor) {
        this.tablaDeSemafor = tablaDeSemafor;
    }

    /**
     * @return the problemasDeCadaSemaforo
     */
    public javax.swing.JList getProblemasDeCadaSemaforo() {
        return problemasDeCadaSemaforo;
    }

    /**
     * @param problemasDeCadaSemaforo the problemasDeCadaSemaforo to set
     */
    public void setProblemasDeCadaSemaforo(JList problemasDeCadaSemaforo) {
        this.problemasDeCadaSemaforo = problemasDeCadaSemaforo;
    }

    /**
     * @return the todosLosProblemas
     */
    public javax.swing.JList getTodosLosProblemas() {
        return todosLosProblemas;
    }

    /**
     * @param todosLosProblemas the todosLosProblemas to set
     */
    public void setTodosLosProblemas(javax.swing.JList todosLosProblemas) {
        this.todosLosProblemas = todosLosProblemas;
    }

    public JComboBox getAltura(){
        return altura;
    }

    public JDialog getPantallaDenunciaExistente(){
        return denunciaExistente;

    }

    public JDialog getPantallaDenunciaGuardad(){
        return denunciaGuardada;

    }

    public JLabel getNumeroDeDenuncia(){
        return numeroDeDenunciaDenunciaExistente;
    }

    public JLabel getCantidadDeReclamos(){
        return cantidadDeReclamosDenunciaExistente;
    }

    public JLabel getDenunciaReclamo(){
        return denunciaReclamo;
    }

    public JLabel getcodigoDenunciaReclamo(){
        return codigoDenunciaReclamo;
    }


    private void ponerTodoEnBlanco(){

        dTOinfoParaCrearDenuncia = new DTOinfoParaCrearDenuncia();
        dTOinfoParaCrearDenuncia.setProblemasDelSemaforo(new ArrayList<DTOProblemasDelSemaforo>());
        hashMapProblemasDelSemaforo = new HashMap<String, DTOProblemasDelSemaforo>();
        //inicializo los combobox de las calles para que esten vacias
        comboCalle1.setModel(new DefaultComboBoxModel());
        comboCalle2.setModel(new DefaultComboBoxModel());
        altura.setModel(new DefaultComboBoxModel());
        //inicializo las listas de problemas para que esten vacias
        todosLosProblemas.setModel(new ModeloJListListaProblemas());
        problemasDeCadaSemaforo.setModel(new ModeloJListListaProblemas());
        //inicializo la tabla de los semaforos
        tablaDeSemafor.setModel(new ModeloTablaSemaforos());
        //inicializo los radio butons, combo box y textbox relacionados a la ubicacion
        interseccionRadioButton.setSelected(true);
        altura.setEnabled(false);
        calle1.setText("");
        calle2.setEditable(true);
        calle2.setText("");
        comboCalle2.setEnabled(true);
        denunciante = null;
        dni.setText("");
        domicilio.setText("");
        telefono.setText("");
        celular.setText("");
        email.setText("");
        apellido.setText("Apellido: ");
        nombre.setText("Nombre: ");
        denunciaGuardada.setLocationRelativeTo(null);
        denunciaGuardada.pack();
        denunciaGuardada.setModal(true);
        denunciaExistente.setLocationRelativeTo(null);
        denunciaExistente.pack();
        denunciaExistente.setModal(true);
        getConsultarAvanceDeReclamo().setEnabled(false);

    }

    public void ponerTodoEnBlancoPublico(){
        ponerTodoEnBlanco();
    }

    /**
     * @return the guardarInfoDenunciante
     */
    public javax.swing.JButton getGuardarInfoDenunciante() {
        return guardarInfoDenunciante;
    }

    /**
     * @param guardarInfoDenunciante the guardarInfoDenunciante to set
     */
    public void setGuardarInfoDenunciante(javax.swing.JButton guardarInfoDenunciante) {
        this.guardarInfoDenunciante = guardarInfoDenunciante;
    }

    /**
     * @return the asentarCaso
     */
    public javax.swing.JButton getAsentarCaso() {
        return asentarCaso;
    }

    /**
     * @param asentarCaso the asentarCaso to set
     */
    public void setAsentarCaso(javax.swing.JButton asentarCaso) {
        this.asentarCaso = asentarCaso;
    }

    /**
     * @return the quitarProblema
     */
    public javax.swing.JButton getQuitarProblema() {
        return quitarProblema;
    }

    /**
     * @param quitarProblema the quitarProblema to set
     */
    public void setQuitarProblema(javax.swing.JButton quitarProblema) {
        this.quitarProblema = quitarProblema;
    }

    /**
     * @return the consultarAvanceDeReclamo
     */
    public javax.swing.JButton getConsultarAvanceDeReclamo() {
        return consultarAvanceDeReclamo;
    }

    /**
     * @param consultarAvanceDeReclamo the consultarAvanceDeReclamo to set
     */
    public void setConsultarAvanceDeReclamo(javax.swing.JButton consultarAvanceDeReclamo) {
        this.consultarAvanceDeReclamo = consultarAvanceDeReclamo;
    }
  


     }
